require('dotenv').config();
require('./config/database');

const Category = require('./models/category');
const Item = require('./models/item');

(async function() {

  await Category.deleteMany({});
  const categories = await Category.create([
    {name: 'gluten-free', sortOrder: 10},
    {name: 'keto-friendly', sortOrder: 20},
    {name: 'paleo', sortOrder: 30},
    {name: 'pescatarian', sortOrder: 40},
    {name: 'vegan', sortOrder: 50},
    {name: 'vegetarian', sortOrder: 60},
  ]);

  await Item.deleteMany({});
  const items = await Item.create([   
  { 
    name: 'banana', 
    calories: '105', 
    edamanId: 'food_bjsfxtcaidvmhaa3afrbna43q3hu', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/9f6/9f6181163a25c96022ee3fc66d9ebb11.jpg',
    qty: '1.0',
    measurementType: 'Medium Banana',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'apple', 
    calories: '95', 
    edamanId: 'food_a1gb9ubb72c7snbuxr3weagwv0dd', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/42c/42c006401027d35add93113548eeaae6.jpg',
    qty: '1.0',
    measurementType: 'Apple',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'asparagus', 
    calories: '48', 
    edamanId: 'food_bpkl8kmahyao17b1pvce5bua1iao', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/9ca/9caf90492f148dc3deee587160c3990e.jpg',
    qty: '12.0',
    measurementType: 'Large Asparagus',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'broccoli', 
    calories: '105', 
    edamanId: 'food_aahw0jha9f8337ajbopx9aec6z7i', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/3e4/3e47317a3dd54dc911b9c44122285df1.jpg',
    qty: '30.0',
    measurementType: 'Florets',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'grapefruit', 
    calories: '104', 
    edamanId: 'food_a5jyw74bd45tgfazfags0akmsjlv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/ac6/ac6139365343036d75bd5999cca5145f.jpg',
    qty: '1.0',
    measurementType: 'Fruit',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'blueberries', 
    calories: '80', 
    edamanId: 'food_b0yuze4b1g3afpanijno5abtiu28', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/984/984a707ea8e9c6bf5f6498970a9e6d9d.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'cherries', 
    calories: '134', 
    edamanId: 'food_bv3hog1bd5qa4oafi7lb3bjz8i92', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/34b/34b23d901752b022d6ab1ee6f9ed0b74.jpg',
    qty: '20.0',
    measurementType: 'Cherries',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'cherry tomatoes', 
    calories: '27', 
    edamanId: 'food_a30b0hpbvavginafe0tocbf6ymje', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/23e/23e727a14f1035bdc2733bb0477efbd2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'cucumber', 
    calories: '18', 
    edamanId: 'food_bv7aggjag9rxsaatklqzobca5fzn', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/501/5015da0e5fc2b384696b3d949aefef86.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'grapes', 
    calories: '54', 
    edamanId: 'food_bncple4a2uagu1b4hov92budz2vs', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/ca5/ca55ac74deb991d159942c65777115df.jpg"https://www.edamam.com/food-img/ca5/ca55ac74deb991d159942c65777115df.jpg',
    qty: '16.0',
    measurementType: 'Grapes',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'mango', 
    calories: '201', 
    edamanId: 'food_an1dqoib8xj3tyb3pr7c0abi4rbw', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/6e0/6e04857756d0876f14bfc035ff238e0b.png',
    qty: '1.0',
    measurementType: 'Mango',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'mixed berries', 
    calories: '65', 
    edamanId: 'food_b0yuze4b1g3afpanijno5abtiu28', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/984/984a707ea8e9c6bf5f6498970a9e6d9d.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'pear', 
    calories: '84', 
    edamanId: 'food_bq6stkiaxkwhxia9q4v7wanjnew0"', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/65a/65aec51d264db28bbe27117c9fdaaca7.jpg',
    qty: '1.0',
    measurementType: '1 Pear, Small',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'pinneapple', 
    calories: '82', 
    edamanId: 'food_b5maw38amr54vpat8d5vhbgmqfxn', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2da/2da6f2397ab64ed185c082edebc4dd7c.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'pomegranate', 
    calories: '144', 
    edamanId: 'food_b43po6ubmv934gb4dfd1kaic8fxa', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/342/342903acce5f863b7683cff3644931a8.jpg',
    qty: '1.0',
    measurementType: 'Cup Arils(Seed/Juice Sacs)',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'raspberries', 
    calories: '56', 
    edamanId: 'food_al3e7s2a1lm4i6bga7o0abp399zg', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/a67/a671e604bed03c27259eab176c781e22.jpg',
    qty: '4.0',
    measurementType: 'Serving (oz)',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'strawberries', 
    calories: '58', 
    edamanId: 'food_b4s2ibkbrrucmbabbaxhfau8ay42', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/00c/00c8851e401bf7975be7f73499b4b573.jpg',
    qty: '10.0',
    measurementType: 'Large Strawberries',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'tomatoes', 
    calories: '22', 
    edamanId: 'food_a6k79rrahp8fe2b26zussa3wtkqh', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/23e/23e727a14f1035bdc2733bb0477efbd2.jpg',
    qty: '1.0',
    measurementType: 'Medium',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'watermelon', 
    calories: '46', 
    edamanId: 'food_aom4czfarp4wsxaeshkohaig1ou5', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e83/e83c09ce97ecd44e00b8c561ab682202.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'fruit'
  },
  { 
    name: 'barley', 
    calories: '193', 
    edamanId: 'food_aqhng66a3do8dqbef41d6bgw6cin', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/9b1/9b1add099acc71e8e7a31be0729b6936.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'bread wheat sprouted', 
    calories: '110', 
    edamanId: 'food_a3049hmbqj5wstaeeb3udaz6uaqv"', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/886/886960f6ce6ccec5b9163bacf2996853.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'brown cooked rice', 
    calories: '327', 
    edamanId: 'food_brqcp7fardef20b44y8riax4k0yz', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/43e/43e669c6de11504972da1ae1898ac19e.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'bulgur wheat', 
    calories: '151', 
    edamanId: 'food_bkevmilaxvl8qubrav0bab1gvbr3', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/183/183954dec093fbb5929dae32031cacc7.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'cooked oatmeal', 
    calories: '166', 
    edamanId: 'food_bd8e66ca0ktqncbnahohzas7tgzg', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/d73/d7368938b793cea3d033553e012be544.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'corn tortillas', 
    calories: '208', 
    edamanId: 'food_bhw0b95agm97s0abfignnb8fsvb3', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/b8a/b8ad23dcc06f2324f944e47eb579d644.jpg',
    qty: '4.0',
    measurementType: 'Tortillas',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'grits', 
    calories: '151', 
    edamanId: 'food_axnhyzqblo14jxabouwarbc2bs7l', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/78c/78ce41c9ac3abdcf8857ba7c5aae47ce.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'quinoa', 
    calories: '222', 
    edamanId: 'food_acc1dplaepqqd3a5wrj6la1s34zw', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/e02/e02246c3856098598f4b7e04fd2d4e4e.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'soba noodles', 
    calories: '113', 
    edamanId: 'food_bjqs981ba4brmoarvdtxaah1pgsl', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/25d/25d50c574c99a627c1b9ade0034fca12.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'whole grain english muffin', 
    calories: '134', 
    edamanId: 'food_bq9xyjcbffze0tao2b3z8a646cp3', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/cac/cac9a071d5da19d9c8b8af9ddaa9a186.jpg',
    qty: '1.0',
    measurementType: 'Muffin',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'whole grain pasta', 
    calories: '238', 
    edamanId: 'food_aup73tlbxslvhwa3ja27ca2gr51o', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/738/73846a8750bb3134aada6b711dc2919d.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'whole grain wheat bread', 
    calories: '100', 
    edamanId: 'food_a3049hmbqj5wstaeeb3udaz6uaqv', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/886/886960f6ce6ccec5b9163bacf2996853.jpg',
    qty: '1.0',
    measurementType: 'Thick Slice',
    caloricDensity: 'green',
    foodType: 'grains'
  },
  { 
    name: 'almond milk', 
    calories: '56', 
    edamanId: 'food_a3049hmbqj5wstaeeb3udaz6uaqv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b26/b267bf598feaabd7349fddda7a481f00.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'coffee', 
    calories: '2', 
    edamanId: 'food_ax0a0yxbbe4hx0apiz1tla01s2w7', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/ee9/ee9566349cb84dfd9ddac1fdf8cbc907.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'kombucha', 
    calories: '34', 
    edamanId: 'food_be4bvp5bk9dn4mbfwpglkb66dexe', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2e2/2e2fe81e1b63a61f6e4adec76220a11b.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'smoothie, fruit only', 
    calories: '161', 
    edamanId: 'food_bglm6vxahuauteb0n6ynfbg9eryu', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e31/e310952d214e78a4cb8b73f30ceeaaf2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'soy latte', 
    calories: '148', 
    edamanId: 'food_a9s841ya6wbvz9a338e34b9a64k7', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2ef/2effbc5aa3e4169159ddc7204026a79e.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'tea', 
    calories: '2', 
    edamanId: 'food_b8aoe5qbgar9fbbcvdj8ea7ekske', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/793/79376cb6e124624e22780db7401601a4.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'vegetable juice', 
    calories: '56', 
    edamanId: 'food_anr6fyyaq3kaztb6an13va45c6sf', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/Xeh9FpH.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'beverages'
  },
  { 
    name: 'bell peppers', 
    calories: '32', 
    edamanId: 'food_a8g63g7ak6bnmvbu7agxibp4a0dy', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/4dc/4dc48b1a506d334b4ab6671b9d56a18f.jpeg',
    qty: '1.0',
    measurementType: 'Pepper',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'brussel sprouts', 
    calories: '28', 
    edamanId: 'food_bkr6xbxbvl7pgua0vy4ibblf93qq', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/28a/28a88a795cd97a3b3b28b65eb8bff5aa.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'cabbage', 
    calories: '22', 
    edamanId: 'food_afb4o8kb767k0iapchxupaifxk1z', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/cb1/cb1411c925c19de26620e63cb90d0e14.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'carrots', 
    calories: '100', 
    edamanId: 'food_buqfaxubzh6hi5asev8a5aj9sr71', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/121/121e33fce0bb9546ed7d060b6c114e29.jpg',
    qty: '4.0',
    measurementType: 'Serving (2 oz per Serving)',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'cauliflower', 
    calories: '3', 
    edamanId: 'food_buqfaxubzh6hi5asev8a5aj9sr71', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/ca2/ca217d31067dffd35ce1215e7f336bd8.jpg',
    qty: '1.0',
    measurementType: 'Floweret',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'celery', 
    calories: '6', 
    edamanId: 'food_bffeoksbyyur8ja4da73ub2xs57g', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/d91/d91d2aed1c36d8fad54c4d7dc58f5a18.jpg',
    qty: '1.0',
    measurementType: 'Stalk',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'green beans', 
    calories: '44', 
    edamanId: 'food_aceucvpau4a8v6atkx5eabxyoqdn', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/891/89135f10639878a2360e6a33c9af3d91.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'green salad', 
    calories: '34', 
    edamanId: 'food_bqalyxzbzu04hcb8xj930bzar7xg', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b6d/b6d9f3052d27a3c71220cfa55c6f0a42.jpg',
    qty: '3.0',
    measurementType: 'Bowl(s)',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'kale', 
    calories: '18', 
    edamanId: 'food_avmg2xfbv1p91yavoxjg7bddvfaz', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/8e9/8e9c5417fa012e5ca068fddc5f8d3d6c.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'lettuce', 
    calories: '8', 
    edamanId: 'food_bf5fxtkbc9alwoajuvsi7amonr5w', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/719/71996625d0cb47e197093ecd52c97dc2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'mixed greens', 
    calories: '8', 
    edamanId: 'food_bqalyxzbzu04hcb8xj930bzar7xg', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b6d/b6d9f3052d27a3c71220cfa55c6f0a42.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'mushrooms', 
    calories: '15', 
    edamanId: 'food_bvlose6arfl26ra396sjrb7hetqh', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/d63/d639cf4a2afc7407c1d1ce286028136b.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'onion', 
    calories: '28', 
    edamanId: 'food_bmrvi4ob4binw9a5m7l07amlfcoy', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/205/205e6bf2399b85d34741892ef91cc603.jpg',
    qty: '1.0',
    measurementType: 'Small Onion',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'peas', 
    calories: '134', 
    edamanId: 'food_bbi35jtbjt7un9bsa2m7eazlsk91', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/5ed/5ed641d646c028598a90bdb9ece34fc8.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'potatoes', 
    calories: '158', 
    edamanId: 'food_b2srd0cbo1zyudatmv3y5ad3umes', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/mdRwfHb.jpg',
    qty: '1.0',
    measurementType: 'Medium',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'spaghetti squash', 
    calories: '126', 
    edamanId: 'food_bj1y3fnbefpaaoagd8c1dad4mdhr', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/bc0/bc073855712255d9478fb9baec6f2afc.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'spinach', 
    calories: '82', 
    edamanId: 'food_aoceuc6bshdej1bbsdammbnj6l6o', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e6e/e6e4be375c4554ce01c8ea75232efaa6.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'sweet potatoes', 
    calories: '110', 
    edamanId: 'food_bg68yf2b3dlfusawgs590bjloxfd', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b66/b660e3d37b4ea9d58cb98e8ea73933b6.jpg',
    qty: '1.0',
    measurementType: 'Sweet Potato',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'zucchini', 
    calories: '21', 
    edamanId: 'food_avpihljbuwpd8ibbmahcabaros5s', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/f63/f637280594e4a731eccc1199194a8847.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'vegetables'
  },
  { 
    name: 'boiled or grilled lobster', 
    calories: '286', 
    edamanId: 'food_bljyewkaowvjseb7k6wctb5a1rrt', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/p1qj3K2.jpg',
    qty: '1.0',
    measurementType: 'Lobster',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'boiled or grilled mahi-mahi', 
    calories: '85', 
    edamanId: 'food_bljyewkaowvjseb7k6wctb5a1rrt', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/3ea/3ea9d821fddd8c398f1dd083f0688864.jpg',
    qty: '1.0',
    measurementType: 'Fillet',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'cooked shrimp', 
    calories: '105', 
    edamanId: 'food_bguh25xb1ibqqha7jdl8ha8ur8mw', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/78e/78e022770d4d46e0fe9e7e3c5a13110c.jpg',
    qty: '20.0',
    measurementType: 'Shrimps',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'crab', 
    calories: '98', 
    edamanId: 'food_aj7w3xab0epj7cbgkbkpwadysovd"', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/c23/c23e20823b442067307aa436969358f1.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'egg whites', 
    calories: '17', 
    edamanId: 'food_ac9n68caswlpggbp7727varlyjk5', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/da5/da5978d61b89a363147a6d13c36e3b54.jpg',
    qty: '1.0',
    measurementType: 'Egg',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'low sodium black beans', 
    calories: '218', 
    edamanId: 'food_bazzo85azdbkmsb56nu4ra5rphoe', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/850/8505bc3d47bbc820b69d532202f61ce1.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'oysters', 
    calories: '11', 
    edamanId: 'food_amv306gav25yjnasnhs0dam6jqcb', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b6a/b6a2846f097ac730b512b3c998abbe7f.jpg',
    qty: '1.0',
    measurementType: 'Serving (21g)',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'tofu', 
    calories: '177', 
    edamanId: 'food_a269ixea1yf51xbfwgnq2boiwc7x', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b6a/b6ae13c3cfe37e16f820840f90231bff.jpg',
    qty: '0.5',
    measurementType: 'Block',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'white fish fillet', 
    calories: '265', 
    edamanId: 'food_aw4231saaagpflaino4iqaumuapc', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/42c/42c99ddd36f31279746f81527d4f982e.jpg',
    qty: '1.0',
    measurementType: 'Fillet',
    caloricDensity: 'green',
    foodType: 'meat protein'
  },
  { 
    name: 'non-fat skim milk', 
    calories: '90', 
    edamanId: 'food_a8p4z9rbx6of06a8zyt4rb0bwyiz', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/525/525c95190fa7373279ac4c9cbfa436a4.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat cheese sticks and slices', 
    calories: '298', 
    edamanId: 'food_bo3fs72aqydlwzadxjbykaahvx3v', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/cc3/cc3c4827d251d79eed1ff87c1861aa34.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat cottage cheese', 
    calories: '160', 
    edamanId: 'food_bo3fs72aqydlwzadxjbykaahvx3v', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/cc3/cc3c4827d251d79eed1ff87c1861aa34.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat cream cheese spread', 
    calories: '302', 
    edamanId: 'food_afw1vv1ac3l17wbn9gcq2autcc91', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/fc7/fc77c17a6b7310e939f328b32dc64e81.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat greek yogurt', 
    calories: '160', 
    edamanId: 'food_bf6arknaq0ne39az8jdf5a24wuhl', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/PfUS8pX.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat half and half', 
    calories: '10', 
    edamanId: 'food_bllwok7blguj59ao7oqp4avjisjc', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/969/96946d091362bcd9a4f86e4cb7ba2ce4.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat sour cream', 
    calories: '12', 
    edamanId: 'food_afw1vv1ac3l17wbn9gcq2autcc91', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/fc7/fc77c17a6b7310e939f328b32dc64e81.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'non-fat yogurt', 
    calories: '173', 
    edamanId: 'food_bllwok7blguj59ao7oqp4avjisjc', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/969/96946d091362bcd9a4f86e4cb7ba2ce4.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'dairy'
  },
  { 
    name: 'chicken bone broth', 
    calories: '41', 
    edamanId: 'food_bb2qjrjamst0vmam39stubtkmrs4', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e61/e6184a8681b772e5198ef0ca1919e1b7.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'beef bone broth', 
    calories: '35', 
    edamanId: 'food_bb2qjrjamst0vmam39stubtkmrs4', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e61/e6184a8681b772e5198ef0ca1919e1b7.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'vegetable bone broth', 
    calories: '13', 
    edamanId: 'food_bitqzx8b319psvbib2dufarphbxy', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/f3f/f3fa6996eba331be219778406f67a5a3.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'butternut squash soup', 
    calories: '220', 
    edamanId: 'food_baga212bywb6n2as0ylgkaf8fcok', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/0aa/0aa76af7d957416d766248b145aa5cbe.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'cabbage soup', 
    calories: '50', 
    edamanId: 'food_afb4o8kb767k0iapchxupaifxk1z', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/cb1/cb1411c925c19de26620e63cb90d0e14.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'homemade chicken noodle soup', 
    calories: '100', 
    edamanId: 'food_ai9u369b0sh4nna64fawma1hs2kf', 
    category: ['keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/d7f/d7f1aed4cb83eae743ea3c781296418f.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'miso soup', 
    calories: '59', 
    edamanId: 'food_bu8imjua16o32cao2m4kravexpo7', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/352/3525e5a38bb13c74aa34ef6c0273bf33.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'spinach soup', 
    calories: '73', 
    edamanId: 'food_aoceuc6bshdej1bbsdammbnj6l6o', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e6e/e6e4be375c4554ce01c8ea75232efaa6.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'tomato and lentil soup', 
    calories: '86', 
    edamanId: 'food_a6k79rrahp8fe2b26zussa3wtkqh', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/23e/23e727a14f1035bdc2733bb0477efbd2.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'vegetable barley soup', 
    calories: '190', 
    edamanId: 'food_bnr1pu6blqhm6lajm0ga6bhl0jvt', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/32b/32baf9bd687a56afd88f726a6dc69882.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'vegetable pho', 
    calories: '352', 
    edamanId: 'food_bitqzx8b319psvbib2dufarphbxy', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/f3f/f3fa6996eba331be219778406f67a5a3.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'soups'
  },
  { 
    name: 'pickles', 
    calories: '7', 
    edamanId: 'food_agcb9ncbucn8q6bq32685ahulbnv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/80b/80b1e5307815f0d9471d86c2e7c36167.jpg',
    qty: '1.0',
    measurementType: 'Pickle',
    caloricDensity: 'green',
    foodType: 'snacks'
  },
  { 
    name: 'unsweetened applesauce', 
    calories: '204', 
    edamanId: 'food_a42ufi8ben9zhqbzqv66lab1lwvd', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/c59/c59e749347516e4aa0aaa3ea25925426.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'green',
    foodType: 'snacks'
  },
  { 
    name: 'buffalo sauce', 
    calories: '1', 
    edamanId: 'food_asvapqhatz4wejanlapyzbmov2k1', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/52c/52cd53c02e0d777330aa795c56230581.jpg',
    qty: '2.0',
    measurementType: 'tsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'hot sauce', 
    calories: '1', 
    edamanId: 'food_a6201h1bu1m0tfbrvis6ma6nvhzv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/946/946c38a4c278da4361d2615d653d685a.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'lemon juice', 
    calories: '1', 
    edamanId: 'food_bglm6vxahuauteb0n6ynfbg9eryu', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e31/e310952d214e78a4cb8b73f30ceeaaf2.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'lime juice', 
    calories: '16', 
    edamanId: 'food_b0iywbmaujvd4eblrooo9bsvn7e6', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/8f0/8f0c10eb3dbf476a05e61018e76ea220.jpg',
    qty: '0.25',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'salsa', 
    calories: '75', 
    edamanId: 'food_b0t3obfawlm5k2b6erxscacez35u', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/995/995d0f166754a0475c181b9c156fec43.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'tomato pasta sauce', 
    calories: '176', 
    edamanId: 'food_a7hv5mybkkrs3ub78yhtxafs67bu', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/08b/08b3bb49c006689a458a8b9c4a4e0057.jpg',
    qty: '1.0',
    measurementType: 'Serving',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'red wine vinegar', 
    calories: '5', 
    edamanId: 'food_ad6iyy1anmzb49a817rgnabnz8c9', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/dc8/dc8e998b32b8d45ba15c1b1e6711e958.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'apple cider vinegar', 
    calories: '6', 
    edamanId: 'food_ar8m7esapmfvf8bnhfzdlabndh6v', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/c7d/c7dbd1846c5d08e9739930d70a404d50.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'rice vinegar', 
    calories: '7', 
    edamanId: 'food_axlcd4tack2d20bveizm4ayu0h2w', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/5f6/5f69b84c399d778c4728e9ab4f8065a2.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'green',
    foodType: 'condiments'
  },
  { 
    name: 'dried apricots', 
    calories: '314', 
    edamanId: 'food_birl02fapy1ae8aywe9qmbsew3d1', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/5f6/5f69b84c399d778c4728e9ab4f8065a2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'fruits'
  },
  { 
    name: 'avocado', 
    calories: '322', 
    edamanId: 'food_b0yuze4b1g3afpanijno5abtiu28', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/984/984a707ea8e9c6bf5f6498970a9e6d9d.jpg',
    qty: '1.0',
    measurementType: 'Avocado',
    caloricDensity: 'yellow',
    foodType: 'fruit'
  },
  { 
    name: 'basmati rice', 
    calories: '205', 
    edamanId: 'food_brqcp7fardef20b44y8riax4k0yz', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/43e/43e669c6de11504972da1ae1898ac19e.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'fried rice', 
    calories: '238', 
    edamanId: 'food_a1q3wkgagst725b4dnamia9v86po', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e0d/e0d970c4dc7a5e0451a98c93e415538a.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'couscous', 
    calories: '176', 
    edamanId: 'food_bhgmmawa1dtqp8anm795pb2n199z', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/0ba/0ba047475ceba632ce566f8997c6f0a5.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'keto bread', 
    calories: '30', 
    edamanId: 'food_a3049hmbqj5wstaeeb3udaz6uaqv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/886/886960f6ce6ccec5b9163bacf2996853.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'low carb tortilla', 
    calories: '70', 
    edamanId: 'food_btkmx91adwv7e0aulg4k0b8xifo7', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/SpIKpit.jpg',
    qty: '1.0',
    measurementType: 'Tortilla',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'lasagna', 
    calories: '401', 
    edamanId: 'food_a35gb18bvghcugb05ylulbjvmj3a', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/e6b/e6be67be9ab596ac7eeb1f9feb54999c.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'white pasta', 
    calories: '505', 
    edamanId: 'food_bcwokz3b2oo23xbi9zcjiav8mo2n', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/222/22205c8592e82a675d90e3673d710bb5.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'noodles', 
    calories: '196', 
    edamanId: 'food_ayweivebq83j17badscbyax7f88x', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/c52/c523bc0bbc9fb862315198af8749be5d.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'whole grain pita bread', 
    calories: '149', 
    edamanId: 'food_bwqktveb77b6uxbrpvxgcb63ucm7', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b8c/b8c2794a59279b7e0553c27e0769fbaf.jpg',
    qty: '1.0',
    measurementType: 'Medium Pita',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'rye bread', 
    calories: '83', 
    edamanId: 'food_ahf32zjb0b6swvahzmtadbi0wht5', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2d1/2d1b8db0fe95a564cb25432a83ca8a66.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'stuffing', 
    calories: '642', 
    edamanId: 'food_bsq0mlmaci65jya0s886xbzqtjxj', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/617/617068594786702e2ccbe7aee824fa5a.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'grains'
  },
  { 
    name: 'ham', 
    calories: '186', 
    edamanId: 'food_acrindvakgdnadbm0hiqbazk46qp', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/004/004c6f6f873dbdcf75b49fc5435bb61b.png',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'salmon fillet', 
    calories: '468', 
    edamanId: 'food_aw4231saaagpflaino4iqaumuapc', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/42c/42c99ddd36f31279746f81527d4f982e.jpg',
    qty: '1.0',
    measurementType: 'Fillet',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'smoked salmon', 
    calories: '23', 
    edamanId: 'food_a9dpcnjb883g67b3lq82ca0421ql', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/474/474d63763b9d8b9da98c5f43a114648c.jpg',
    qty: '1.0',
    measurementType: 'Piece',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'tuna salad', 
    calories: '383', 
    edamanId: 'food_aaluhexb6hatm8a0x8eoaaf5v647', 
    category: ['gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://i.imgur.com/toXjwcP.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'roast beef', 
    calories: '474', 
    edamanId: 'food_ax7kea5b64jkulbmusq5rbg8hr7o', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/91a/91a096319265361432d1e6b40c16c42c.jpg',
    qty: '1.0',
    measurementType: 'Slice (7 oz per Slice)',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'beef steak', 
    calories: '471', 
    edamanId: 'food_akt4a0rbmqy1f8ae8t02xaydsbob', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/7a1/7a1dd7cab2cb1d3342bccfdc7c858b94.jpg',
    qty: '1.0',
    measurementType: 'Serving (6 oz per Serving)',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'rotisserie chicken', 
    calories: '260', 
    edamanId: 'food_b5zsm7lb1vq961b5d7azga71z5gx', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/f75/f758d06ecbf92550af64e25af5689d96.jpg',
    qty: '1.0',
    measurementType: 'Chicken',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'chicken', 
    calories: '335', 
    edamanId: 'food_bjvk9deb1xaifybk52mrna7gb7v4', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://i.imgur.com/zDjCl1H.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'turkey breast', 
    calories: '166', 
    edamanId: 'food_at1qxqra2bs2wxa2lb60zb355f99', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2ee/2eeaf7c0f554159cde70dde625d9dceb.jpg',
    qty: '1.0',
    measurementType: 'Serving (4 oz per Serving)',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'ground turkey', 
    calories: '169', 
    edamanId: 'food_ayn3tcxa8ddppqbjsr95pbwsewm0', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://i.imgur.com/Q4byjUW.png',
    qty: '1.0',
    measurementType: 'Patty',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'turkey sausage', 
    calories: '147', 
    edamanId: 'food_brauuuyazjfx14bvzr989bvxd63y', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/182/18209b4b31a37a3aaa2b8d5a2fa5fae0.jpg',
    qty: '1.0',
    measurementType: 'Link',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'egg salad', 
    calories: '471', 
    edamanId: 'food_ac9n68caswlpggbp7727varlyjk5', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/da5/da5978d61b89a363147a6d13c36e3b54.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'hard boiled egg', 
    calories: '78', 
    edamanId: 'food_bljyewkaowvjseb7k6wctb5a1rrt', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/3ea/3ea9d821fddd8c398f1dd083f0688864.jpg',
    qty: '1.0',
    measurementType: 'Egg',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'lean pork loin', 
    calories: '188', 
    edamanId: 'food_ax7kea5b64jkulbmusq5rbg8hr7o', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/91a/91a096319265361432d1e6b40c16c42c.jpg',
    qty: '1.0',
    measurementType: 'Serving (4 oz per Serving)',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'lean pork chop', 
    calories: '259', 
    edamanId: 'food_bnmkkwqa9h2p87bz171eoby0bsey', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/d4e/d4e8110d51db4311bc894167a8f77816.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'pulled pork', 
    calories: '418', 
    edamanId: 'food_ax7kea5b64jkulbmusq5rbg8hr7o"', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/91a/91a096319265361432d1e6b40c16c42c.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'meat proteins'
  },
  { 
    name: 'low fat cottage cheese', 
    calories: '180', 
    edamanId: 'food_a9tqku4bsbj3gsad6mjdobrjsamu', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/0df/0df8aad6c445fe1069fb243fa182b7b6.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'dairy'
  },
  { 
    name: 'low fat yogurt', 
    calories: '216', 
    edamanId: 'food_a9tqku4bsbj3gsad6mjdobrjsamu', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/0df/0df8aad6c445fe1069fb243fa182b7b6.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'dairy'
  },
  { 
    name: 'low fat milk', 
    calories: '102', 
    edamanId: 'food_bfbjttnbf8cdwjabmp83ibuutl92', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/f85/f859cce57955d778ccb5d0224e08cf93.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'dairy'
  },
  { 
    name: 'canned corn', 
    calories: '177', 
    edamanId: 'food_b26mh3ubkdgxt3bcvqqu3a0mm6fr', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/59c/59c4373175b468d87ac76a43d4349b57.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'fried mushrooms', 
    calories: '150', 
    edamanId: 'food_b4dfihfa1ejmrpbq8ls53b0n1dmg', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/7dd/7ddc18efbecc5bb44fb638b2af17e148.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'grilled onions', 
    calories: '211', 
    edamanId: 'food_b5pq504arby3emb1a2mjjaar54l8', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/5f1/5f18e93c02bcf4eab14620febb53b5a2.png',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'roasted potatoes', 
    calories: '180', 
    edamanId: 'food_bbu83kha8tvy32br7mr28b4hdkp5', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/956/9561f54f6ba83ad619e9830487107b29.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'mashed potatoes', 
    calories: '237', 
    edamanId: 'food_bqgfv5na1p5qwgaddkx9xbe5bf4l', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/3ba/3bad90497524770195b335d288d4a7e1.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'plantains', 
    calories: '205', 
    edamanId: 'food_b5390qwao5mc3yanbn3a1afp6vs8', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/a89/a895e325e16d684d8df7786aa7898f73.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'yams', 
    calories: '177', 
    edamanId: 'food_bvm8fxwb5tu279am6lgw3bqvzqsb', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/530/5301e2fd59307812cbd5276de724d6aa.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'pickled beets', 
    calories: '148', 
    edamanId: 'food_a09hufoahq3o7latketmta9xeqo7', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/2c5/2c513e67af460b7f5ebe53028ceb8a37.jpg',
    qty: '1.0',
    measurementType: 'Cup Slices',
    caloricDensity: 'yellow',
    foodType: 'vegetables'
  },
  { 
    name: 'black-eyed peas', 
    calories: '120', 
    edamanId: 'food_bg7d14ha9q9wh5a0nwmn4as6jwb2', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/7d0/7d0c43eab42a9e30db3bf3b53aa0203d.jpg',
    qty: '1.0',
    measurementType: 'Serving',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'black beans', 
    calories: '227', 
    edamanId: 'food_ba7qnuqak7imykabthyouaa7cjjd', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/9d8/9d803ebe9881e45fad3f70d877780ad5.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'chickpeas', 
    calories: '269', 
    edamanId: 'food_blvf434an6ms21akuaezeagzs3k8', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/59c/59c1e8fa37680d54775d3a8013eb7db6.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'edamame', 
    calories: '188', 
    edamanId: 'food_ax3xe7sabd02azaxpqx0ybpgk308', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/087/0871875e6db6422656a70b250640157a.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'hummus', 
    calories: '333', 
    edamanId: 'food_bvver0jaktvay3amv02gval1xqnm', 
    category: ['vegan', 'vegetarian', 'pescatarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/dd4/dd46febae7d039955a22d2e278293f41.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'lentils', 
    calories: '230', 
    edamanId: 'food_bg13k5uafva4jta78xnjcaqkli85', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/d5a/d5aa5bc5a3142f3179f31310054a56e6.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'legume and seeds'
  },
  { 
    name: 'broccoli cheddar soup', 
    calories: '433', 
    edamanId: 'food_aahw0jha9f8337ajbopx9aec6z7i', 
    category: ['vegetarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/3e4/3e47317a3dd54dc911b9c44122285df1.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'chicken tortilla soup', 
    calories: '260', 
    edamanId: 'food_bhw0b95agm97s0abfignnb8fsvb3', 
    category: ['gluten-free', 'paleo'],    
    image: 'https://www.edamam.com/food-img/b8a/b8ad23dcc06f2324f944e47eb579d644.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'cream of mushroom soup', 
    calories: '410', 
    edamanId: 'food_bnr1pu6blqhm6lajm0ga6bhl0jvt', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/32b/32baf9bd687a56afd88f726a6dc69882.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'new england clam chowder', 
    calories: '402', 
    edamanId: 'food_b5m473aabh39qbbre3ypaa4uwd7j', 
    category: ['gluten-free', 'paleo'],    
    image: 'https://www.edamam.com/food-img/651/6512e82417bce15c2899630c1a2799df.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'split pea soup', 
    calories: '191', 
    edamanId: 'food_bn08gvkay09vqoalwgv3naakbv8e', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/7a4/7a4b8d233d32da8afde3e94bbf1e214f.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'tomato bisque soup', 
    calories: '285', 
    edamanId: 'food_a0wg2dnb8zg5ypb6idfhnatpxyy0', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'pescatarian', 'paleo'],    
    image: 'https://www.edamam.com/food-img/056/0562051b49da4937cb41afeba32edb81.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'turkey noodle soup', 
    calories: '257', 
    edamanId: 'food_bwjbcwjasc41zza3rdnt9bm0pmc0', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/c52/c523bc0bbc9fb862315198af8749be5d.jpg',
    qty: '1.0',
    measurementType: 'Serving (16 oz per Serving)',
    caloricDensity: 'yellow',
    foodType: 'soups'
  },
  { 
    name: 'balsamic vinegar', 
    calories: '14', 
    edamanId: 'food_b1ic8tzapja8jubas1f8lbhpbn6x', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/90a/90a1f211768e166ecfff19e8b4747498.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'guacamole', 
    calories: '293', 
    edamanId: 'food_bflwu59aqjdfhzbgqr68qai8mgk8', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'pescatarian', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/fc8/fc804ddb3fdf4b07f414b6ca930fb1b2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'ketchup', 
    calories: '17', 
    edamanId: 'food_au7jthtab0n3era9uue8pauakroe', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/257/257207c446011b849001ae596390341c.jpeg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'low sodium soy sauce', 
    calories: '10', 
    edamanId: 'food_af8xwhdbq4vg0tbqfqjysafu339b"', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/4bc/4bccc4c294a8dddb62020c62935e6fd8.jpg',
    qty: '1.0',
    measurementType: 'Serving',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'mustard', 
    calories: '3', 
    edamanId: 'food_a34cdj5b0kyuhfbov30xcb50u4dv', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/e23/e238f2e4cfa6aa1a30f46dc73e7344eb.jpg',
    qty: '1.0',
    measurementType: 'tsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'sriracha', 
    calories: '18', 
    edamanId: 'food_a6201h1bu1m0tfbrvis6ma6nvhzv', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/946/946c38a4c278da4361d2615d653d685a.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'soy sauce, tamari', 
    calories: '15', 
    edamanId: 'food_a5g9yevb1iactoaiimbvjbkrxueh', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/f56/f562e461eb0618f367f538b836c17b82.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'splenda, stevia', 
    calories: '1', 
    edamanId: 'food_b8xzxmtb5f98f1bqswelta92yfk6', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://i.imgur.com/McDVbBt.jpg',
    qty: '1.0',
    measurementType: 'Packet',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'sweet pickle relish', 
    calories: '15', 
    edamanId: 'food_bdpk447bepyyfma1ali5qbk50zqp', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/210/210a09427be497df1915356d63d91d8b.jpeg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'worcestershire sauce', 
    calories: '13', 
    edamanId: 'food_asvapqhatz4wejanlapyzbmov2k1', 
    category: ['gluten-free', 'keto-friendly', 'paleo'],    
    image: 'https://www.edamam.com/food-img/52c/52cd53c02e0d777330aa795c56230581.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'yellow',
    foodType: 'condiments'
  },
  { 
    name: 'avocado toast', 
    calories: '189', 
    edamanId: 'food_b0yuze4b1g3afpanijno5abtiu28', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/984/984a707ea8e9c6bf5f6498970a9e6d9d.jpg',
    qty: '1.0',
    measurementType: 'Piece',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'bread and butter pickles', 
    calories: '14', 
    edamanId: 'food_bd06g1pbfdev9ja50blv6a5524ye', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/012/0121cf9d4ee772af299f450bf577a8d3.jpeg',
    qty: '1.0',
    measurementType: 'Pickle',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'caesar salad', 
    calories: '192', 
    edamanId: 'food_aaluhexb6hatm8a0x8eoaaf5v647', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian'],    
    image: 'https://i.imgur.com/HqTOile.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'coleslaw', 
    calories: '348', 
    edamanId: 'food_bwbxnnqbuk1re9ateh4lwbwlg1zv', 
    category: ['other'],    
    image: 'https://i.imgur.com/qqksuTR.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'greek salad', 
    calories: '179', 
    edamanId: 'food_aaluhexb6hatm8a0x8eoaaf5v647', 
    category: ['vegetarian', 'paleo', 'gluten-free', 'pescatarian', 'keto-friendly'],    
    image: 'https://i.imgur.com/FlHntvu.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'kale salad', 
    calories: '84', 
    edamanId: 'food_avmg2xfbv1p91yavoxjg7bddvfaz', 
    category: ['vegan', 'vegetarian', 'gluten-free', 'pescatarian', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/8e9/8e9c5417fa012e5ca068fddc5f8d3d6c.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'pasta salad', 
    calories: '407', 
    edamanId: 'food_a8hs60uayl5icia1qe8qoba1kwp8', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/296/296ff2b02ef3822928c3c923e22c7d19.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'popcorn', 
    calories: '44', 
    edamanId: 'food_btstgycbd4sqzma2c239qaeuy5at', 
    category: ['vegan', 'vegetarian'],    
    image: 'https://www.edamam.com/food-img/dd5/dd51dd3656053985cf1c47ca5c75c4db.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'potato salad', 
    calories: '358', 
    edamanId: 'food_abiw5baauresjmb6xpap2bg3otzu', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/651/6512e82417bce15c2899630c1a2799df.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'sugar-free chocolate pudding', 
    calories: '70', 
    edamanId: 'food_bo37p69bopqshvaul0bn4bv0kqni', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/ced/ced25c45453a118e531c8aaf33e2ee38.jpg',
    qty: '1.0',
    measurementType: 'Pudding',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'sushi', 
    calories: '349', 
    edamanId: 'food_bot0mjyb2tvaugbdj6pd5b0571yj', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/c7d/c7dbd1846c5d08e9739930d70a404d50.jpg',
    qty: '1.0',
    measurementType: 'Roll',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'turkey sandwich', 
    calories: '310', 
    edamanId: 'food_a9rj5w6aiih82zbzhr0ujauniccy', 
    category: ['paleo'],    
    image: 'https://www.edamam.com/food-img/78f/78ffbae0365a1a431061ff397c3b6d38.jpg',
    qty: '1.0',
    measurementType: 'Sandwich',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'veggie pizza', 
    calories: '170', 
    edamanId: 'food_aobepaeayqrwd9ab9zr8haovx9u7', 
    category: ['vegan', 'vegetarian', 'paleo', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/fca/fca7ed551530a613b5e218f2f21c408f.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'black coffee with splenda, stevia, equal', 
    calories: '4', 
    edamanId: 'food_b8xzxmtb5f98f1bqswelta92yfk6', 
    category: ['other'],    
    image: 'https://i.imgur.com/zLlnF7Y.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'tea with milk, splenda, stevia', 
    calories: '20', 
    edamanId: 'food_b8xzxmtb5f98f1bqswelta92yfk6', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://i.imgur.com/GXMIOeR.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'snacks'
  },
  { 
    name: 'chai tea', 
    calories: '4', 
    edamanId: 'food_btq38w0axmrjyearqs6c8ayrmiy8', 
    category: ['vegan', 'vegetarian', 'paleo', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/035/035a537e8e579556ba54f6f6e77cc1f2.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'club soda', 
    calories: '150', 
    edamanId: 'food_ae33wnvaild66dawgxsqlbcrp02x', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/0c7/0c7ea246f0c3b05641539fd1861c1c20.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'soda', 
    calories: '1', 
    edamanId: 'food_ae33wnvaild66dawgxsqlbcrp02x', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/0c7/0c7ea246f0c3b05641539fd1861c1c20.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'diet soda', 
    calories: '1', 
    edamanId: 'food_apeevqhakhtdtxaaj5vwcbgj6idg', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/9b4/9b4a1ab566697c212af64b33b3f6c938.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'IPA beer', 
    calories: '197', 
    edamanId: 'food_b3ieo81b7uf59ya5529oobsaaqbu', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/7f8/7f82e3944cd8fcba3ffad7b6ce741c62.jpg',
    qty: '1.0',
    measurementType: 'Bottle',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'lager beer', 
    calories: '99', 
    edamanId: 'food_apdzzzhaiwpy13akj1lucbiatrwe', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/7f8/7f82e3944cd8fcba3ffad7b6ce741c62.jpg',
    qty: '1.0',
    measurementType: 'Serving',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'lemonade', 
    calories: '99', 
    edamanId: 'food_bgtb3yaase2fz2adiqy3fbppepnj', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/311/3118a3ddad625ac41009a59ff610e6da.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'oat milk latte', 
    calories: '95', 
    edamanId: 'food_aunfnxjahcjg50aaywnbsaa5jf14', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/457/457087c973dd41ba1b08854c355ec183.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'orange juice', 
    calories: '112', 
    edamanId: 'food_bn7zicravp7kdrb8h9knhadt6kei', 
    category: ['vegan', 'vegetarian', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/011/011c0c3b0f3865bde575f57c556439e4.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'rum and diet coke', 
    calories: '87', 
    edamanId: 'food_bi9pqpkbrb86k8aowifmbbxwzgng', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/eb5/eb51e606b36b62c66ea1a245ab0d4a8b.jpg',
    qty: '1.0',
    measurementType: 'Rock Glass (8 fl oz)',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'soy milk', 
    calories: '100', 
    edamanId: 'food_ajck21hbpf1sb6amwkjimb6xl24j', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/8be/8bef4cf5daa1f41d90aff68c92ca56bc.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'super green smoothie', 
    calories: '112', 
    edamanId: 'food_bhypx5aahx13snbg2kn00br14i86', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://i.imgur.com/r6SIBCq.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'tonic water', 
    calories: '114', 
    edamanId: 'food_au3ld0ybd8hhrtbfpcbhya63cjps', 
    category: ['vegan', 'vegetarian', 'paleo', 'gluten-free', 'pescatarian', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/b59/b59c5aed899795bee3f7778433b511e3.jpg',
    qty: '1.0',
    measurementType: 'Bottle',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'unsweetened apple juice', 
    calories: '114', 
    edamanId: 'food_ai7w4okaoeknd5b5j9o66bm6nu10', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/324/32497d8cd6291a6f03acc032e1da7676.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'vodka soda', 
    calories: '54', 
    edamanId: 'food_aqnx4i8aieyph2athk58cb3cr69w', 
    category: ['vegan', 'vegetarian', 'paleo', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/e1a/e1a4708099e89fdadeb81c2d95deaa34.jpg',
    qty: '1.0',
    measurementType: 'Cocktail Glass',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'wine', 
    calories: '122', 
    edamanId: 'food_bw5p1agbubb4dubpm8r0yax8fjco', 
    category: ['vegan', 'vegetarian', 'paleo', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/aeb/aebdd2e72bc13fa8ca762a408b6e58b6.jpg',
    qty: '1.0',
    measurementType: 'Wine Glass',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'ginger ale', 
    calories: '124', 
    edamanId: 'food_ae09oqiazn7tlbb0x5yiebtmfslr', 
    category: ['vegan', 'vegetarian', 'paleo', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/81d/81d3a248c4ca048ffabc9551cc96217d.jpg',
    qty: '1.0',
    measurementType: 'Can',
    caloricDensity: 'yellow',
    foodType: 'beverages'
  },
  { 
    name: 'dried cranberries', 
    calories: '410', 
    edamanId: 'food_atvsjvja2h9xyfblcy3pzaienr8a', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/8aa/8aa3935a527394e1568079a489759221.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'fruits'
  },
  { 
    name: 'raisins', 
    calories: '956', 
    edamanId: 'food_a3qcdxyb09op1hbwstv5cbmoqc3d', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian', 'gluten-free', 'keto-friendly'],    
    image: 'https://www.edamam.com/food-img/159/159e247350db62e1f87b0636a53687f5.jpg',
    qty: '1.0',
    measurementType: 'Bowl',
    caloricDensity: 'red',
    foodType: 'fruits'
  },
  { 
    name: 'french fries', 
    calories: '173', 
    edamanId: 'food_aqa4qtwapci86kar0l275bjqmkal', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/559/559b143365bf3dde8d5889ec627e1da7.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'vegetables'
  },
  { 
    name: 'french onions', 
    calories: '584', 
    edamanId: 'food_bmrvi4ob4binw9a5m7l07amlfcoy', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/205/205e6bf2399b85d34741892ef91cc603.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'vegetables'
  },
  { 
    name: 'french pickles', 
    calories: '50', 
    edamanId: 'food_agcb9ncbucn8q6bq32685ahulbnv', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/80b/80b1e5307815f0d9471d86c2e7c36167.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'vegetables'
  },
  { 
    name: 'sweet potato fries', 
    calories: '298', 
    edamanId: 'food_bg68yf2b3dlfusawgs590bjloxfd', 
    category: ['vegan', 'vegetarian', 'paleo', 'pescatarian'],    
    image: 'https://www.edamam.com/food-img/b66/b660e3d37b4ea9d58cb98e8ea73933b6.jpg',
    qty: '20.0',
    measurementType: 'Fries',
    caloricDensity: 'red',
    foodType: 'vegetables'
  },
  { 
    name: 'butter', 
    calories: '100', 
    edamanId: 'food_bg68yf2b3dlfusawgs590bjloxfd', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/b66/b660e3d37b4ea9d58cb98e8ea73933b6.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'cottage cheese', 
    calories: '214', 
    edamanId: 'food_af0p1geb3didvtbqvc2bvby1evye', 
    category: ['other'],    
    image: 'https://i.imgur.com/g1GPdj0.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'dairy cream', 
    calories: '30', 
    edamanId: 'food_afw1vv1ac3l17wbn9gcq2autcc91', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/fc7/fc77c17a6b7310e939f328b32dc64e81.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'cream cheese', 
    calories: '51', 
    edamanId: 'food_afw1vv1ac3l17wbn9gcq2autcc91', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/fc7/fc77c17a6b7310e939f328b32dc64e81.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'cheddar cheese', 
    calories: '110', 
    edamanId: 'food_ak5zq1kbxhob25bsqpc1ta89eswy', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/af8/af88890facab925abf729a73714f6ea9.png',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'full fat yogurt', 
    calories: '61', 
    edamanId: 'food_bwav9tzazb4bjhamv1vk1ajgsgrw', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/9bd/9bd861dbd83731bc03091a30f09f9728.jpg',
    qty: '1.0',
    measurementType: 'Serving (100g)',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'half and half', 
    calories: '18', 
    edamanId: 'food_b32v6b1al0f6wwaxoeqwvau3fb44', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/c22/c22242b5b81b78d4cb2996946ee9459c.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'margarine', 
    calories: '102', 
    edamanId: 'food_bmgvd8ebe85l7ybbyb7gob2y2w1k', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/e1d/e1deed85a7d1c9132466ea4513ee3070.jpg',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'sour cream', 
    calories: '24', 
    edamanId: 'food_b7r68adakprkpxa1rd3rtb33wvaj', 
    category: ['other'],    
    image: 'https://i.imgur.com/R6Q4D7w.png',
    qty: '1.0',
    measurementType: 'tbsp',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'whole milk', 
    calories: '149', 
    edamanId: 'food_brp5d14al1mexqa3m52cabvn94j3', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/e4f/e4f167fbcac1ff50cd68d187de638b35.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'dairy'
  },
  { 
    name: 'all-purpose flour', 
    calories: '455', 
    edamanId: 'food_ar3x97tbq9o9p6b6gzwj0am0c81l', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/368/368077bbcab62f862a8c766a56ea5dd1.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'bagel', 
    calories: '277', 
    edamanId: 'food_abgmon9a80fjy1b5vyx0kawkj6n1', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/755/7553666b2864e4003538607529dcccde.jpg',
    qty: '1.0',
    measurementType: 'Bagel',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'flour tortilla', 
    calories: '159', 
    edamanId: 'food_a9ql6pdb639bs5b2nlvbob3w0mlj', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/357/357e415685787e6d6844e8d08c1b1586.jpg',
    qty: '1.0',
    measurementType: 'Tortilla',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'garlic bread', 
    calories: '206', 
    edamanId: 'food_bq9xyjcbffze0tao2b3z8a646cp3', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/cac/cac9a071d5da19d9c8b8af9ddaa9a186.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'granola', 
    calories: '596', 
    edamanId: 'food_b34qe9ya35sl0oawlmwdmaalkwhh', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/c1d/c1ddb4084dd26bd5fa47e01bb49ed6a8.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'muffins', 
    calories: '117', 
    edamanId: 'food_bq9xyjcbffze0tao2b3z8a646cp3', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/cac/cac9a071d5da19d9c8b8af9ddaa9a186.jpg',
    qty: '1.0',
    measurementType: 'Muffin',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'banana bread', 
    calories: '247', 
    edamanId: 'food_bjkzbiraxq9ak4bofb7jvaoxi3co', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/869/869d807713fe1d7daf40ed31b843245a.jpg',
    qty: '1.0',
    measurementType: 'Piece',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'rolls and buns', 
    calories: '76', 
    edamanId: 'food_bqej00dajarrgpb1l32xhacc4kbn', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/78f/78ffbae0365a1a431061ff397c3b6d38.jpg',
    qty: '1.0',
    measurementType: 'Roll',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'sourdough', 
    calories: '116', 
    edamanId: 'food_ay7f6vxa98k5w2ahve8h1ardjn1w', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/470/47053c77e167539c64fef3f2a3249bb2.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'sweetened oatmeal', 
    calories: '136', 
    edamanId: 'food_bd8e66ca0ktqncbnahohzas7tgzg', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/d73/d7368938b793cea3d033553e012be544.jpg',
    qty: '1.0',
    measurementType: 'Cup',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'waffle', 
    calories: '218', 
    edamanId: 'food_a9tbnggaptgl18ahj21qtbb0frw4', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/f0b/f0bbafeabcca46f1fcd1cea65794c524.png',
    qty: '1.0',
    measurementType: 'Waffle',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'white breads', 
    calories: '65', 
    edamanId: 'food_a3049hmbqj5wstaeeb3udaz6uaqv', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/886/886960f6ce6ccec5b9163bacf2996853.jpg',
    qty: '1.0',
    measurementType: 'Slice',
    caloricDensity: 'red',
    foodType: 'grains'
  },
  { 
    name: 'butter', 
    calories: '298', 
    edamanId: 'food_bg68yf2b3dlfusawgs590bjloxfd', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/b66/b660e3d37b4ea9d58cb98e8ea73933b6.jpg',
    qty: '20.0',
    measurementType: 'Fries',
    caloricDensity: 'red',
    foodType: 'meat proteins'
  },
  { 
    name: 'butter', 
    calories: '298', 
    edamanId: 'food_bg68yf2b3dlfusawgs590bjloxfd', 
    category: ['other'],    
    image: 'https://www.edamam.com/food-img/b66/b660e3d37b4ea9d58cb98e8ea73933b6.jpg',
    qty: '20.0',
    measurementType: 'Fries',
    caloricDensity: 'red',
    foodType: 'dairy'
  },

  
 
  
  ]);

  console.log(items)

  process.exit();

})();